[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "taxometr"
version = '0.1.0'
authors = [
  { name = "Youriy Volkov", email = "atribolt@gmail.com" }
]
requires-python = "~=3.10"
readme = "README.md"
license = { file = 'LICENSE' }
dependencies = [
    "peewee~=3.17.9"
]

[project.optional-dependencies]
postgres = ['psycopg2-binary']
dev = ['nuitka', 'ruff']
test = ['pytest']
